#ifndef NARAD_MUNI_SOURCES_H
#define NARAD_MUNI_SOURCES_H


//================================================= NARAD Source/Root Start =================================================//
// Before rename/update macro for source/root
// must be statically updated for load case extraction for source/root info

#define MACRO_NARAD_Evidence_Type_QString                             "MACRO_NARAD_Evidence_Type_QString"
#define MACRO_NARAD_Root_Evidence_Number_QString                      "MACRO_NARAD_Root_Evidence_Number_QString"
#define MACRO_NARAD_Root_Description_QString                          "MACRO_NARAD_Root_Description_QString"
#define MACRO_NARAD_Root_Count_Name_QString                           "MACRO_NARAD_Root_Count_Name_QString"
#define MACRO_NARAD_Root_Type_QString                                 "MACRO_NARAD_Root_Type_QString"
#define MACRO_NARAD_Root_Source_Type_Display_QString                  "MACRO_NARAD_Root_Source_Type_Display_QString"
#define MACRO_NARAD_Root_Source_Type_Internal_QString                 "MACRO_NARAD_Root_Source_Type_Internal_QString"
#define MACRO_NARAD_Root_Name_QString                                 "MACRO_NARAD_Root_Name_QString"
#define MACRO_NARAD_Root_Path_1_QString                               "MACRO_NARAD_Root_Path_1_QString"
#define MACRO_NARAD_Root_Path_2_for_fusion_QString                    "MACRO_NARAD_Root_Path_2_for_fusion_QString"
#define MACRO_NARAD_Root_Recovery_Passcode_Encrypted_QString          "MACRO_NARAD_Root_Recovery_Passcode_Encrypted_QString"
#define MACRO_NARAD_Root_Evidence_Password_Encrypted_QString          "MACRO_NARAD_Root_Evidence_Password_Encrypted_QString"

#define MACRO_NARAD_Root_Hash_MD5_QString                             "MACRO_NARAD_Root_Hash_MD5_QString"
#define MACRO_NARAD_Root_Hash_SHA1_QString                            "MACRO_NARAD_Root_Hash_SHA1_QString"
#define MACRO_NARAD_Root_Source_Count_Name_All_QStringList            "MACRO_NARAD_Root_Source_Count_Name_All_QStringList"
#define MACRO_NARAD_Root_Source_Count_Name_Prime_QStringList          "MACRO_NARAD_Root_Source_Count_Name_Prime_QStringList"
#define MACRO_NARAD_Root_Source_Count_Name_Nested_QStringList         "MACRO_NARAD_Root_Source_Count_Name_Nested_QStringList"
#define MACRO_NARAD_Root_Home_Directory_Given_User_Name_QString       "MACRO_NARAD_Root_Home_Directory_Given_User_Name_QString"
#define MACRO_NARAD_Root_Disk_Node_1_QString                          "MACRO_NARAD_Root_Disk_Node_1_QString"
#define MACRO_NARAD_Root_Disk_Identifier_1_QString                    "MACRO_NARAD_Root_Disk_Identifier_1_QString"
#define MACRO_NARAD_Root_Disk_Node_2_for_fusion_QString               "MACRO_NARAD_Root_Disk_Node_2_for_fusion_QString"
#define MACRO_NARAD_Root_Disk_Identifier_2_for_fusion_QString         "MACRO_NARAD_Root_Disk_Identifier_2_for_fusion_QString"

#define MACRO_NARAD_Source_RUNTIME_Root_Recovery_Passcode_Plain_QString  "MACRO_NARAD_Source_RUNTIME_Root_Recovery_Passcode_Plain_QString"
#define MACRO_NARAD_Source_Evidence_Password_Encrypted_QString           "MACRO_NARAD_Source_Evidence_Password_Encrypted_QString"

#define MACRO_NARAD_Source_OS_Scheme_Display_QString                  "MACRO_NARAD_Source_OS_Scheme_Display_QString"
#define MACRO_NARAD_Source_OS_Scheme_Internal_QString                 "MACRO_NARAD_Source_OS_Scheme_Internal_QString"
#define MACRO_NARAD_Source_Type_Display_QString                       "MACRO_NARAD_Source_Type_Display_QString"
#define MACRO_NARAD_Source_Type_Internal_QString                      "MACRO_NARAD_Source_Type_Internal_QString"
#define MACRO_NARAD_Source_Path_1_QString                             "MACRO_NARAD_Source_Path_1_QString"
#define MACRO_NARAD_Source_Path_2_For_Fusion_QString                  "MACRO_NARAD_Source_Path_2_For_Fusion_QString"
#define MACRO_NARAD_Source_Used_Space_Byte_Numeric_QString            "MACRO_NARAD_Source_Used_Space_Byte_Numeric_QString"
#define MACRO_NARAD_Source_Free_Space_Byte_Numeric_QString            "MACRO_NARAD_Source_Free_Space_Byte_Numeric_QString"
#define MACRO_NARAD_Source_File_System_Type_QString                   "MACRO_NARAD_Source_File_System_Type_QString"
#define MACRO_NARAD_Source_Volume_Type_QString                        "MACRO_NARAD_Source_Volume_Type_QString"
#define MACRO_NARAD_Source_Volume_Offset_QString                      "MACRO_NARAD_Source_Volume_Offset_QString"
#define MACRO_NARAD_Source_Volume_UUID_QString                        "MACRO_NARAD_Source_Volume_UUID_QString"
#define MACRO_NARAD_Source_Total_Size_Byte_Numeric_QString            "MACRO_NARAD_Source_Total_Size_Byte_Numeric_QString"
#define MACRO_NARAD_Source_Disk_Identifier_QString                    "MACRO_NARAD_Source_Disk_Identifier_QString"
#define MACRO_NARAD_Source_Nested_bool                                "MACRO_NARAD_Source_Nested_bool"
#define MACRO_NARAD_Source_Hierarchy_QString                          "MACRO_NARAD_Source_Hierarchy_QString"
#define MACRO_NARAD_Source_Decompressed_bool                          "MACRO_NARAD_Source_Decompressed_bool"
#define MACRO_NARAD_Source_Main_Name_QString                          "MACRO_NARAD_Source_Main_Name_QString"
#define MACRO_NARAD_Source_Name_QString                               "MACRO_NARAD_Source_Name_QString"
#define MACRO_NARAD_Source_Main_Path_QString                          "MACRO_NARAD_Source_Main_Path_QString"
#define MACRO_NARAD_Source_Virtual_Source_Path_QString                "MACRO_NARAD_Source_Virtual_Source_Path_QString"
#define MACRO_NARAD_Source_System_Account_QList                       "MACRO_NARAD_Source_System_Account_QList"
#define MACRO_NARAD_Source_Time_Zone_Readable_QString                 "MACRO_NARAD_Source_Time_Zone_Readable_QString"
#define MACRO_NARAD_Source_Time_Zone_Numeric_qint64                   "MACRO_NARAD_Source_Time_Zone_Numeric_qint64"
#define MACRO_NARAD_Source_Product_Type_QString                       "MACRO_NARAD_Source_Product_Type_QString"
#define MACRO_NARAD_Source_OS_Version_Extended_QString                "MACRO_NARAD_Source_OS_Version_Extended_QString"
#define MACRO_NARAD_Source_OS_Version_Full_QString                    "MACRO_NARAD_Source_OS_Version_Full_QString"
#define MACRO_NARAD_Source_Country_QString                            "MACRO_NARAD_Source_Country_QString"
#define MACRO_NARAD_Source_City_QString                               "MACRO_NARAD_Source_City_QString"
#define MACRO_NARAD_Source_Latitude_QString                           "MACRO_NARAD_Source_Latitude_QString"
#define MACRO_NARAD_Source_Longitude_QString                          "MACRO_NARAD_Source_Longitude_QString"
#define MACRO_NARAD_Source_Configured_ID_QStringList                  "MACRO_NARAD_Source_Configured_ID_QStringList"
#define MACRO_NARAD_Source_Device_Name_QString                        "MACRO_NARAD_Source_Device_Name_QString"
#define MACRO_NARAD_Source_Id_No_QString                              "MACRO_NARAD_Source_Id_No_QString"
#define MACRO_NARAD_Source_GUID_QString                               "MACRO_NARAD_Source_GUID_QString"
#define MACRO_NARAD_Source_Target_Type_QString                        "MACRO_NARAD_Source_Target_Type_QString"
#define MACRO_NARAD_Source_Build_Version_QString                      "MACRO_NARAD_Source_Build_Version_QString"
#define MACRO_NARAD_Source_iTune_Version_QString                      "MACRO_NARAD_Source_iTune_Version_QString"
#define MACRO_NARAD_Source_Imei_QStringList                           "MACRO_NARAD_Source_Imei_QStringList"
#define MACRO_NARAD_Source_Phone_No_MSISDN_QStringList                "MACRO_NARAD_Source_Phone_No_MSISDN_QStringList"
#define MACRO_NARAD_Source_Serial_No_QString                          "MACRO_NARAD_Source_Serial_No_QString"
#define MACRO_NARAD_Source_Backup_Size_Byte_Numeric_QString           "MACRO_NARAD_Source_Backup_Size_Byte_Numeric_QString"
#define MACRO_NARAD_Source_Latest_Backup_Date_Readable_QString        "MACRO_NARAD_Source_Latest_Backup_Date_Readable_QString"
#define MACRO_NARAD_Source_Latest_Backup_Date_Numeric_qint64          "MACRO_NARAD_Source_Latest_Backup_Date_Numeric_qint64"
#define MACRO_NARAD_Source_Product_Name_QString                       "MACRO_NARAD_Source_Product_Name_QString"
#define MACRO_NARAD_Source_Sim_No_Iccid_QStringList                   "MACRO_NARAD_Source_Sim_No_Iccid_QStringList"
#define MACRO_NARAD_Source_Display_Name_QString                       "MACRO_NARAD_Source_Display_Name_QString"
#define MACRO_NARAD_Source_Count_Name_QString                         "MACRO_NARAD_Source_Count_Name_QString"
#define MACRO_NARAD_Source_Snapshots_APFS_QStringList                 "MACRO_NARAD_Source_Snapshots_APFS_QStringList"
#define MACRO_NARAD_Source_RECON_Logical_Mode_bool                    "MACRO_NARAD_Source_RECON_Logical_Mode_bool"
#define MACRO_NARAD_Source_OS_Installer_Timestamp_UTC_Numeric_qint64    "MACRO_NARAD_Source_OS_Installer_Timestamp_UTC_Numeric_qint64"

#define MACRO_NARAD_Source_Product_Model_QString                      "MACRO_NARAD_Source_Product_Model_QString"
#define MACRO_NARAD_Source_Bluetooth_Device_Address_QString           "MACRO_NARAD_Source_Bluetooth_Device_Address_QString"
#define MACRO_NARAD_Source_Wifi_Address_QString                       "MACRO_NARAD_Source_Wifi_Address_QString"
#define MACRO_NARAD_Source_Locale_Language_QString                    "MACRO_NARAD_Source_Locale_Language_QString"
#define MACRO_NARAD_Source_Role_Type_QString                          "MACRO_NARAD_Source_Role_Type_QString"

#endif // NARAD_MUNI_SOURCES_H
