#ifndef HEADER_GLOBAL_VARIABLES_2_H
#define HEADER_GLOBAL_VARIABLES_2_H

#include "narad_muni/narad_muni.h"


extern narad_muni *global_narad_muni_class_obj;

const extern QString global_variable_private_var_tmp_Dir_Path_Parent_QString;
const extern QString global_variable_private_var_tmp_Dir_Path_Case_QString;
const extern QString global_varibale_python_path;


extern bool global_variable_debug_mode_status_bool;
extern bool global_variable_debug_encryption_status_bool;
extern bool global_variable_debug_print_on_terminal_bool;
extern bool global_variable_debug_print_in_file_bool;
extern bool global_variable_debug_type_general_bool;
extern bool global_variable_debug_type_conditional_bool;
extern bool global_variable_debug_type_intensive_bool;

extern bool global_variable_macOS_appearance_light_mode_bool;
extern bool global_variable_desktop_silicon_bool;

#endif // HEADER_GLOBAL_VARIABLES_2_H
